In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('https://github.com/HamoyeHQ/HDSC-Introduction-to-Python-for-machine-learning/files/7768140/FoodBalanceSheets_E_Africa_NOFLAG.csv', encoding='latin-1')

In [ ]:
df.tail(10)

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
60933,181,Zimbabwe,2899,Miscellaneous,5611,Import Quantity,1000 tonnes,42.00,47.00,33.00,15.00,16.00
60934,181,Zimbabwe,2899,Miscellaneous,5072,Stock Variation,1000 tonnes,0.00,0.00,0.00,-4.00,0.00
60935,181,Zimbabwe,2899,Miscellaneous,5911,Export Quantity,1000 tonnes,1.00,1.00,0.00,0.00,1.00
60936,181,Zimbabwe,2899,Miscellaneous,5301,Domestic supply quantity,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60937,181,Zimbabwe,2899,Miscellaneous,5170,Residuals,1000 tonnes,0.00,0.00,0.00,0.00,0.00
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [ ]:
df.isnull().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [ ]:
df.duplicated().any()

False

In [ ]:
df.shape

(60943, 12)

In [ ]:
len(df)

60943

In [ ]:
df.rename(columns = {'Area Code':'Area_Code','Item Code':'Item_Code','Element Code':'Element_Code'}, inplace = True)

In [ ]:
df.head()

,Area_Code,Area,Item_Code,Item,Element_Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [ ]:
features1=['Element_Code','Y2014','Y2015', 'Y2016', 'Y2017','Y2018']
res = df[features1].corr()

In [ ]:
res.iloc[0].min()

0.02344399758496104

In [ ]:
lst = [[35, 'Portugal', 94], [33, 'Argentina', 93], [30 , 'Brazil', 92]]
col = ['Age','Nationality','Overall']
df2 = pd.DataFrame(lst, columns = col, index = [i for i in range(1,4)])

In [ ]:
df2

   Age Nationality  Overall
1   35    Portugal       94
2   33   Argentina       93
3   30      Brazil       92

In [ ]:
df.groupby('Area')['Y2017'].sum().sort_values(ascending= False)

Area
Nigeria                        1483268.23
Egypt                           866379.92
South Africa                    517590.54
Ethiopia                        448683.76
Morocco                         388495.36
Ghana                           337599.06
Algeria                         325644.27
United Republic of Tanzania     322616.85
Kenya                           264660.66
Sudan                           239931.92
Cameroon                        232030.43
Angola                          229159.57
Côte d'Ivoire                   224599.01
Uganda                          213950.38
Malawi                          181098.71
Mozambique                      161407.98
Mauritania                      156665.46
Mali                            149928.33
Madagascar                      131197.73
Niger                           126707.58
Benin                           124771.22
Tunisia                         124167.20
Zambia                          103223.77
Burkina Faso                    101855.07
Guinea                           98138.87
Senegal                          95681.15
Zimbabwe                         75919.34
Rwanda                           73663.69
Chad                             71594.68
Sierra Leone                     55311.33
Eswatini                         54343.33
Mauritius                        51114.83
Togo                             49841.88
Congo                            41181.68
Central African Republic         29937.00
Namibia                          29874.89
Liberia                          29342.20
Gabon                            27979.64
Gambia                           23154.18
Djibouti                         22729.91
Botswana                         22101.30
Lesotho                          21267.96
Guinea-Bissau                    19102.77
Cabo Verde                       14650.74
Sao Tome and Principe            12662.63
Seychelles                         442.34
Comoros                             59.84
Sudan (former)                       0.00
Ethiopia PDR                         0.00
Name: Y2017, dtype: float64

In [ ]:
df.iloc[10:12]

,Area_Code,Area,Item_Code,Item,Element_Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
10,4,Algeria,2941,Animal Products,684,Fat supply quantity (g/capita/day),g/capita/day,26.22,24.64,25.37,24.6,22.71
11,4,Algeria,2905,Cereals - Excluding Beer,5511,Production,1000 tonnes,3436.00,3761.00,3445.00,3478.0,6065.00

In [ ]:
y = [(2, 4), (7, 8), (1, 5, 9)]
x = y[1][-1]
print(x)

8

In [ ]:
df.groupby('Element')['Y2017'].sum()

Element
Domestic supply quantity                  2088198.10
Export Quantity                            182338.80
Fat supply quantity (g/capita/day)          10253.84
Feed                                       223705.68
Food                                      1258888.28
Food supply (kcal/capita/day)              454681.00
Food supply quantity (kg/capita/yr)         48690.04
Import Quantity                            294559.09
Losses                                     160614.00
Other uses (non-food)                       91645.97
Processing                                 292836.00
Production                                2030056.89
Protein supply quantity (g/capita/day)      11842.45
Residuals                                   35500.00
Seed                                        24870.14
Stock Variation                             54316.91
Total Population - Both sexes             1112641.00
Tourist consumption                            91.00
Name: Y2017, dtype: float64

In [ ]:
df.Area.nunique()

49

In [ ]:
S = [['him', 'sell'], [90, 28, 43]]
S[0][1][1]

'e'

In [ ]:
df[df.Area == 'Madagascar']

,Area_Code,Area,Item_Code,Item,Element_Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
30715,129,Madagascar,2501,Population,511,Total Population - Both sexes,1000 persons,23590.00,24234.00,24894.00,25571.00,26262.00
30716,129,Madagascar,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
30717,129,Madagascar,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,1986.00,1922.00,1918.00,1943.00,1938.00
30718,129,Madagascar,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,44.45,43.26,43.35,43.94,44.17
30719,129,Madagascar,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,22.18,22.97,23.83,25.26,24.12
...,...,...,...,...,...,...,...,...,...,...,...,...
32149,129,Madagascar,2899,Miscellaneous,5142,Food,1000 tonnes,10.00,11.00,11.00,11.00,12.00
32150,129,Madagascar,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,0.44,0.44,0.44,0.44,0.44
32151,129,Madagascar,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,0.00,0.00,0.00,0.00,0.00
32152,129,Madagascar,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.01,0.01,0.01,0.01,0.01
32153,129,Madagascar,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.01,0.01,0.01,0.01,0.01

In [ ]:
df[df.Area == 'Madagascar'].groupby('Element')['Y2015'].sum()

Element
Domestic supply quantity                  31214.98
Export Quantity                             494.75
Fat supply quantity (g/capita/day)           91.85
Feed                                       2070.22
Food                                      21120.65
Food supply (kcal/capita/day)              7685.00
Food supply quantity (kg/capita/yr)         871.59
Import Quantity                            1721.80
Losses                                     2176.00
Other uses (non-food)                      3957.12
Processing                                 1803.00
Production                                29482.89
Protein supply quantity (g/capita/day)      173.05
Residuals                                  -616.00
Seed                                        699.00
Stock Variation                            -505.00
Total Population - Both sexes             24234.00
Name: Y2015, dtype: float64

In [ ]:
df.Y2017.describe()

count     59437.000000
mean        140.917765
std        1671.862359
min       -1582.000000
25%           0.000000
50%           0.100000
75%           9.000000
max      190873.000000
Name: Y2017, dtype: float64

In [ ]:
df.groupby('Element')[['Y2014',	'Y2015',	'Y2016',	'Y2017',	'Y2018']].sum().iloc[15].sort_values(ascending= False)

Y2014    58749.83
Y2017    54316.91
Y2015    34910.99
Y2016    33140.12
Y2018    20577.91
Name: Stock Variation, dtype: float64

In [ ]:
my_tuppy = (1,2,5,8)
my_tuppy[2] = 6 #unmutable!!!

TypeError: 'tuple' object does not support item assignment

In [ ]:
array  = np.array([[94, 89, 63],

             [93, 92, 48],

             [92, 94, 56]])
array[:2,1:]

array([[89, 63],
       [92, 48]])

In [ ]:
df.groupby('Area')['Y2017'].sum().sort_values()

Area
Sudan (former)                       0.00
Ethiopia PDR                         0.00
Comoros                             59.84
Seychelles                         442.34
Sao Tome and Principe            12662.63
Cabo Verde                       14650.74
Guinea-Bissau                    19102.77
Lesotho                          21267.96
Botswana                         22101.30
Djibouti                         22729.91
Gambia                           23154.18
Gabon                            27979.64
Liberia                          29342.20
Namibia                          29874.89
Central African Republic         29937.00
Congo                            41181.68
Togo                             49841.88
Mauritius                        51114.83
Eswatini                         54343.33
Sierra Leone                     55311.33
Chad                             71594.68
Rwanda                           73663.69
Zimbabwe                         75919.34
Senegal                          95681.15
Guinea                           98138.87
Burkina Faso                    101855.07
Zambia                          103223.77
Tunisia                         124167.20
Benin                           124771.22
Niger                           126707.58
Madagascar                      131197.73
Mali                            149928.33
Mauritania                      156665.46
Mozambique                      161407.98
Malawi                          181098.71
Uganda                          213950.38
Côte d'Ivoire                   224599.01
Angola                          229159.57
Cameroon                        232030.43
Sudan                           239931.92
Kenya                           264660.66
United Republic of Tanzania     322616.85
Algeria                         325644.27
Ghana                           337599.06
Morocco                         388495.36
Ethiopia                        448683.76
South Africa                    517590.54
Egypt                           866379.92
Nigeria                        1483268.23
Name: Y2017, dtype: float64

In [ ]:
df.groupby('Item')[['Y2015','Y2018']].sum()

                         Y2015      Y2018
Item
Alcohol, Non-Food      2180.00    2293.00
Alcoholic Beverages   98783.72   97847.27
Animal Products       11811.73   11578.61
Animal fats          200675.72  269648.27
Apples and products   10559.15    9640.51
...                        ...        ...
Vegetables, Other    158104.08  163987.21
Vegetal Products     107064.17  107775.39
Wheat and products   234710.51  242645.19
Wine                   4251.81    4039.32
Yams                 203151.78  221272.09

[119 rows x 2 columns]